### ISSUE TITLE
Vrchat OpenBeta 1212でlaunch.exeがクラッシュしてしまう

### ISSUE THREAD

**Issue by Zel9278** [yanorei32/VRChatRejoinTool#24]
Launchを押すと、launch.exeがクラッシュしてVRChatが起動してこない

スクリーンショット
https://files.csys64.com/ucgt.png

環境
OS: Windows Server 2012 R2(Version 6.3 / Build 9600)
CPU: Intel Xeon E3-1220 v3
RAM: 16GB
GPU: GTX1050Ti

**Comment by yanorei32** [comment]
仕様ではないでしょうか。

https://docs.vrchat.com/v2022.2.2/docs/latest-release
> During Open Beta, you must launch VRChat via special launch options in Steam. This will not be the case when the update goes to Live

**Comment by yanorei32** [comment]
対応状況は #23 にて閲覧可能です。

この Issue は Close してよろしいでしょうか？

**Comment by Zel9278** [comment]
大丈夫です、すみません。
